### ISSUE TITLE
Even with app_launch_url, didn't enable Singpass App to return to RP mobile app automatically

### ISSUE THREAD

**Issue by TheinHtikeAung** [singpass/iOS-Singpass-in-app-browser-login-demo#8]
I tried by adding app_launch_url in MyInfo v3 authorise api. But it didn't work.
May I know if any additional steps need to follow? 
Thanks in advance. 
![Screenshot 2023-08-07 at 11 56 50 AM](https://github.com/singpass/iOS-Singpass-in-app-browser-login-demo/assets/1689662/84b9fad8-82c5-46a5-b8f4-a7445095ca2d)

**Comment by chinweekoh** [comment]
Hi @TheinHtikeAung , if you are on MyInfo v3 try with `appLaunchURL` instead of `app_launch_url`

**Comment by TheinHtikeAung** [comment]
Thanks @chinweekoh for the reply. Recently found out that as well and working well now.
